---
apiVersion: v1
kind: Service
metadata:
  name: bind-svc-udp
  namespace: bind
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-10.2.0.105"
spec:
  selector:
    app: bind
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 10.2.0.105
---
apiVersion: v1
kind: Service
metadata:
  name: bind-svc-tcp
  namespace: bind
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-10.2.0.105"
spec:
  selector:
    app: bind
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 10.2.0.105
