---
apiVersion: v1
kind: Service
metadata:
  name: bind-service
spec:
  type: LoadBalancer
  selector:
    app: bind
  ports:
    # By default and for convenience, the `targetPort`
    # is set to the same value as the `port` field.
    - port: 53
      targetPort: 53
      nodePort: 30053
      protocol: UDP
      name: dns-udp
      loadBalancerIP: 10.2.0.105
    - port: 53
      targetPort: 53
      nodePort: 30053
      protocol: TCP
      name: dns-tcp
      loadBalancerIP: 10.2.0.105
